# -*- coding: utf-8 -*-
"""Copy of Copy of Send_Birthdate_Emails .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OP1GEM_J5mDBXqF1F0Ih0TRc8raTHfHP
"""

# Description this program sends Happy birthday emails messages to list of friends

# Import the libraries
import datetime
import pandas as pd
import numpy as np
import smtplib
import ssl
import subprocess
import sys
import os
port = 465  # for SSL_context
from email.mime.text import MIMEText as MT
from email.mime.multipart import MIMEMultipart as MM

# Function to install a package using pip
def install(package):
    subprocess.check_call([sys.executable, "-m", "pip", "install", package])

# Try to import gdown, if it fails, install it
try:
    import gdown
except ImportError:
    install('gdown')
    import gdown

# Download the file from Google Drive and save it as Birthday.xlsx
gdown.download("https://drive.google.com/uc?id=1x41YjiGJYonh8vI_ULXa0ExJ99WhHz6w", "Birthday.xlsx", quiet=False)

# Read in the data
df = pd.read_excel('Birthday.xlsx')

# Show the data
print(df)

# Create a function to send emails
def email_func(subject, birthday_receiver, name):
    # Store the email address for the receiver and the sender, Also store the sender's email password
    receiver = birthday_receiver
    sender = 'odaniyan@oauife.edu.ng'
    sender_password = 'Mxdanren05'

    # Create a MIMEMultipart object
    msg = MM()
    msg['Subject'] = subject + ' ' + str(name) + '!'

    # Create the HTML for the message
    HTML = """
    <html>
    <body>
        <h1> Happy Birthday!</h1>
        <img src="https://storcpdkenticomedia.blob.core.windows.net/media/recipemanagementsystem/media/recipe-media-files/recipes/retail/x17/16714-birthday-cake-600x600.jpg?ext=.jpg" alt="image" width="640" height="360"></img>
        <p>Photo by: sugar-Daze</p>
        <h2>
            <p>Hello,<br>
            I hope you have a wonderful day today!<br><br>
            From;<br>
            Your Friend
        </h2>
    </body>
    </html>
    """

    # Create an HTML MIMEText object
    MTObj = MT(HTML, "html")

    # Attach the MIMEText object into the message container
    msg.attach(MTObj)

    # Create a secure connection with the server and send the email
    # Create the secure socket layer (SSL) context object
    SSL_context = ssl.create_default_context()
    # Create the secure simple Mail Transfer Protocol(SMTP) connection
    server = smtplib.SMTP_SSL(host='smtp.gmail.com', port=465, context=SSL_context)

    # Login to the email account
    server.login(sender, sender_password)
    # Send the email
    server.sendmail(sender, receiver, msg.as_string())
    server.quit()

# Get today's date
today = datetime.date.today()
# Get the current year
year = today.year

# Loop through the birthday list to send emails to friends whose birthdays are today
for i in range(len(df)):
    # Get the person's month
    month = df['Birth_Month'][i]
    # Get the person's day of birth
    day = df['Birth_Day'][i]
    # Get the person's name
    name = df['Name'][i]
    # Get the person's email address
    email = df['Email'][i]
    # Get the person's birthdate
    birthdate = datetime.date(year, month, day)
    # Check if today is that person's birthday
    if birthdate == today:
        email_func('Happy Birthday', email, name)
        print(f'Sent happy birthday to {name}')
    else:
        print(f'Did not send happy birthday to {name}')

